### ISSUE TITLE
cssnano removes vh units.

### ISSUE THREAD

**Issue by Xaviju** [ben-eb/cssnano#12]
I'm using cssnano to minify this CSS code (with postcss)

```css
.hero {
    height: 80vh;
}
```

When I add **cssnano** and minify the CSS it removes this attribute if its value its expressed in vh.
If I disable cssnano it works ok.
If I change the value to PX or % it works correctly.

Thanks!

**Comment by TrySound** [comment]
@Xaviju Markup doesn't work in code.

**Comment by Xaviju** [comment]
Yeah, sorry, fast edition :sweat_smile: 

Thanks!

**Comment by TrySound** [comment]
@Xaviju Thanks for your catch!

**Comment by ben-eb** [comment]
Fixed. Could you please confirm?

**Comment by Xaviju** [comment]
Is it updated on npm? I updated to the latest version available ```'cssnano": "1.0.2"``` and still not working.
Thanks for the fast response!

**Comment by ben-eb** [comment]
@Xaviju The fix is in `postcss-convert-values@1.2.2` - make sure you have that version installed. :smile:
